a = input('Digite qualquer coisa: ')
print('O tipo primitivo é: ',type(a))
print('Só tem espacos?', a.isspace())
print('É um número?', a.isnumeric())
print('É alfabetico?', a.isalpha())
print('É alfanúmerico?', a.isalnum())
print('Está maiuscula?', a.isupper())
print('Está minuscula?', a.islower())
print('Está capitalizada?',a.istitle())