nome = str(input('Digite seu nome completo: ')).strip()
maius = nome.upper()
minus = nome.lower()
prinome = nome.split()
print('Seu nome em maiúsculas é {}'.format(maius))
print('Seu nome em minúsculas é {}'.format(minus))
print('Seu nome tem ao todo {} letras'.format(len(nome) - nome.count(' ')))
#print('Seu primeiro nome é {} e tem {} letras'.format(prinome[0],len(prinome[0])))
print('Seu primerio nome tem {} letras'.format(nome.find(' ')))